# Allow these licenses by default

ACCEPTABLE_LICENSES+=	ruby-license
ACCEPTABLE_LICENSES+=	unrar-license
ACCEPTABLE_LICENSES+=	unarj-license
ACCEPTABLE_LICENSES+=	zoo-license
ACCEPTABLE_LICENSES+=	sendmail-open-source-license
ACCEPTABLE_LICENSES+=	lame-license
ACCEPTABLE_LICENSES+=	corecode-license
ACCEPTABLE_LICENSES+=	sendmail-license
ACCEPTABLE_LICENSES+=	erlang-public-license
ACCEPTABLE_LICENSES+=	vim-license
ACCEPTABLE_LICENSES+=	boost
ACCEPTABLE_LICENSES+=	p5-Crypt-Blowfish-license
ACCEPTABLE_LICENSES+=	php-license
ACCEPTABLE_LICENSES+=	openldap-license
ACCEPTABLE_LICENSES+=	sleepycat-license
ACCEPTABLE_LICENSES+=	jasper-license
ACCEPTABLE_LICENSES+=	jpeg-license
ACCEPTABLE_LICENSES+=	netpbm-license
ACCEPTABLE_LICENSES+=	openssl-license
ACCEPTABLE_LICENSES+=	dcc-free-license
ACCEPTABLE_LICENSES+=	uemacs-license
ACCEPTABLE_LICENSES+=	urw-fonts-license
ACCEPTABLE_LICENSES+=	openmotif-license
ACCEPTABLE_LICENSES+=	idea-license

# The Aladdin Free Public License is not free, see here:
# http://www.artifex.com/downloads/doc/Public.htm
ACCEPTABLE_LICENSES+=	aladdin-license

# Sun Binary License (needed for the sun-libc a.k.a.
# SUNWlibC package)
ACCEPTABLE_LICENSES+=	opensolaris-binary-license

# Sun Distributor License for Java
ACCEPTABLE_LICENSES+=	sun-distributor-java-license
